// Code generated by go-swagger; DO NOT EDIT.

package meta

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewIndexesUsingGETParams creates a new IndexesUsingGETParams object
// with the default values initialized.
func NewIndexesUsingGETParams() *IndexesUsingGETParams {

	return &IndexesUsingGETParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewIndexesUsingGETParamsWithTimeout creates a new IndexesUsingGETParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewIndexesUsingGETParamsWithTimeout(timeout time.Duration) *IndexesUsingGETParams {

	return &IndexesUsingGETParams{

		timeout: timeout,
	}
}

// NewIndexesUsingGETParamsWithContext creates a new IndexesUsingGETParams object
// with the default values initialized, and the ability to set a context for a request
func NewIndexesUsingGETParamsWithContext(ctx context.Context) *IndexesUsingGETParams {

	return &IndexesUsingGETParams{

		Context: ctx,
	}
}

// NewIndexesUsingGETParamsWithHTTPClient creates a new IndexesUsingGETParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewIndexesUsingGETParamsWithHTTPClient(client *http.Client) *IndexesUsingGETParams {

	return &IndexesUsingGETParams{
		HTTPClient: client,
	}
}

/*IndexesUsingGETParams contains all the parameters to send to the API endpoint
for the indexes using g e t operation typically these are written to a http.Request
*/
type IndexesUsingGETParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the indexes using g e t params
func (o *IndexesUsingGETParams) WithTimeout(timeout time.Duration) *IndexesUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the indexes using g e t params
func (o *IndexesUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the indexes using g e t params
func (o *IndexesUsingGETParams) WithContext(ctx context.Context) *IndexesUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the indexes using g e t params
func (o *IndexesUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the indexes using g e t params
func (o *IndexesUsingGETParams) WithHTTPClient(client *http.Client) *IndexesUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the indexes using g e t params
func (o *IndexesUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *IndexesUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
