// Code generated by go-swagger; DO NOT EDIT.

package meta

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/michalq/go-airly-api-client/models"
)

// IndexesUsingGETReader is a Reader for the IndexesUsingGET structure.
type IndexesUsingGETReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IndexesUsingGETReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewIndexesUsingGETOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewIndexesUsingGETOK creates a IndexesUsingGETOK with default headers values
func NewIndexesUsingGETOK() *IndexesUsingGETOK {
	return &IndexesUsingGETOK{}
}

/*IndexesUsingGETOK handles this case with default header values.

List of IndexTypes
*/
type IndexesUsingGETOK struct {
	Payload []*models.IndexType
}

func (o *IndexesUsingGETOK) Error() string {
	return fmt.Sprintf("[GET /v2/meta/indexes][%d] indexesUsingGETOK  %+v", 200, o.Payload)
}

func (o *IndexesUsingGETOK) GetPayload() []*models.IndexType {
	return o.Payload
}

func (o *IndexesUsingGETOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
