// Code generated by go-swagger; DO NOT EDIT.

package meta

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/michalq/go-airly-api-client/models"
)

// MeasurementsUsingGETReader is a Reader for the MeasurementsUsingGET structure.
type MeasurementsUsingGETReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MeasurementsUsingGETReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewMeasurementsUsingGETOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewMeasurementsUsingGETOK creates a MeasurementsUsingGETOK with default headers values
func NewMeasurementsUsingGETOK() *MeasurementsUsingGETOK {
	return &MeasurementsUsingGETOK{}
}

/*MeasurementsUsingGETOK handles this case with default header values.

List of MeasurementTypes
*/
type MeasurementsUsingGETOK struct {
	Payload []*models.MeasurementType
}

func (o *MeasurementsUsingGETOK) Error() string {
	return fmt.Sprintf("[GET /v2/meta/measurements][%d] measurementsUsingGETOK  %+v", 200, o.Payload)
}

func (o *MeasurementsUsingGETOK) GetPayload() []*models.MeasurementType {
	return o.Payload
}

func (o *MeasurementsUsingGETOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
