// Code generated by go-swagger; DO NOT EDIT.

package measurements

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/michalq/go-airly-api-client/models"
)

// MapPointMeasurementsUsingGETReader is a Reader for the MapPointMeasurementsUsingGET structure.
type MapPointMeasurementsUsingGETReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MapPointMeasurementsUsingGETReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewMapPointMeasurementsUsingGETOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewMapPointMeasurementsUsingGETOK creates a MapPointMeasurementsUsingGETOK with default headers values
func NewMapPointMeasurementsUsingGETOK() *MapPointMeasurementsUsingGETOK {
	return &MapPointMeasurementsUsingGETOK{}
}

/*MapPointMeasurementsUsingGETOK handles this case with default header values.

Point measurements interpolated from nearby Installations
*/
type MapPointMeasurementsUsingGETOK struct {
	Payload *models.Measurements
}

func (o *MapPointMeasurementsUsingGETOK) Error() string {
	return fmt.Sprintf("[GET /v2/measurements/point][%d] mapPointMeasurementsUsingGETOK  %+v", 200, o.Payload)
}

func (o *MapPointMeasurementsUsingGETOK) GetPayload() *models.Measurements {
	return o.Payload
}

func (o *MapPointMeasurementsUsingGETOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Measurements)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
