// Code generated by go-swagger; DO NOT EDIT.

package measurements

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewNearestUsingGET1Params creates a new NearestUsingGET1Params object
// with the default values initialized.
func NewNearestUsingGET1Params() *NearestUsingGET1Params {
	var (
		indexTypeDefault     = string("AIRLY_CAQI")
		latDefault           = float64(50.062006)
		lngDefault           = float64(19.940984)
		maxDistanceKMDefault = float64(3)
	)
	return &NearestUsingGET1Params{
		IndexType:     &indexTypeDefault,
		Lat:           latDefault,
		Lng:           lngDefault,
		MaxDistanceKM: &maxDistanceKMDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewNearestUsingGET1ParamsWithTimeout creates a new NearestUsingGET1Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewNearestUsingGET1ParamsWithTimeout(timeout time.Duration) *NearestUsingGET1Params {
	var (
		indexTypeDefault     = string("AIRLY_CAQI")
		latDefault           = float64(50.062006)
		lngDefault           = float64(19.940984)
		maxDistanceKMDefault = float64(3)
	)
	return &NearestUsingGET1Params{
		IndexType:     &indexTypeDefault,
		Lat:           latDefault,
		Lng:           lngDefault,
		MaxDistanceKM: &maxDistanceKMDefault,

		timeout: timeout,
	}
}

// NewNearestUsingGET1ParamsWithContext creates a new NearestUsingGET1Params object
// with the default values initialized, and the ability to set a context for a request
func NewNearestUsingGET1ParamsWithContext(ctx context.Context) *NearestUsingGET1Params {
	var (
		indexTypeDefault     = string("AIRLY_CAQI")
		latDefault           = float64(50.062006)
		lngDefault           = float64(19.940984)
		maxDistanceKMDefault = float64(3)
	)
	return &NearestUsingGET1Params{
		IndexType:     &indexTypeDefault,
		Lat:           latDefault,
		Lng:           lngDefault,
		MaxDistanceKM: &maxDistanceKMDefault,

		Context: ctx,
	}
}

// NewNearestUsingGET1ParamsWithHTTPClient creates a new NearestUsingGET1Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewNearestUsingGET1ParamsWithHTTPClient(client *http.Client) *NearestUsingGET1Params {
	var (
		indexTypeDefault     = string("AIRLY_CAQI")
		latDefault           = float64(50.062006)
		lngDefault           = float64(19.940984)
		maxDistanceKMDefault = float64(3)
	)
	return &NearestUsingGET1Params{
		IndexType:     &indexTypeDefault,
		Lat:           latDefault,
		Lng:           lngDefault,
		MaxDistanceKM: &maxDistanceKMDefault,
		HTTPClient:    client,
	}
}

/*NearestUsingGET1Params contains all the parameters to send to the API endpoint
for the nearest using g e t 1 operation typically these are written to a http.Request
*/
type NearestUsingGET1Params struct {

	/*IndexType
	  Select index which should be returned in response

	*/
	IndexType *string
	/*Lat
	  Latitude

	*/
	Lat float64
	/*Lng
	  Longitude

	*/
	Lng float64
	/*MaxDistanceKM
	  Max distance in km. Negative values mean 'infinity' (no results limit). Optional parameter, if omitted defaults to 3km.

	*/
	MaxDistanceKM *float64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the nearest using g e t 1 params
func (o *NearestUsingGET1Params) WithTimeout(timeout time.Duration) *NearestUsingGET1Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the nearest using g e t 1 params
func (o *NearestUsingGET1Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the nearest using g e t 1 params
func (o *NearestUsingGET1Params) WithContext(ctx context.Context) *NearestUsingGET1Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the nearest using g e t 1 params
func (o *NearestUsingGET1Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the nearest using g e t 1 params
func (o *NearestUsingGET1Params) WithHTTPClient(client *http.Client) *NearestUsingGET1Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the nearest using g e t 1 params
func (o *NearestUsingGET1Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIndexType adds the indexType to the nearest using g e t 1 params
func (o *NearestUsingGET1Params) WithIndexType(indexType *string) *NearestUsingGET1Params {
	o.SetIndexType(indexType)
	return o
}

// SetIndexType adds the indexType to the nearest using g e t 1 params
func (o *NearestUsingGET1Params) SetIndexType(indexType *string) {
	o.IndexType = indexType
}

// WithLat adds the lat to the nearest using g e t 1 params
func (o *NearestUsingGET1Params) WithLat(lat float64) *NearestUsingGET1Params {
	o.SetLat(lat)
	return o
}

// SetLat adds the lat to the nearest using g e t 1 params
func (o *NearestUsingGET1Params) SetLat(lat float64) {
	o.Lat = lat
}

// WithLng adds the lng to the nearest using g e t 1 params
func (o *NearestUsingGET1Params) WithLng(lng float64) *NearestUsingGET1Params {
	o.SetLng(lng)
	return o
}

// SetLng adds the lng to the nearest using g e t 1 params
func (o *NearestUsingGET1Params) SetLng(lng float64) {
	o.Lng = lng
}

// WithMaxDistanceKM adds the maxDistanceKM to the nearest using g e t 1 params
func (o *NearestUsingGET1Params) WithMaxDistanceKM(maxDistanceKM *float64) *NearestUsingGET1Params {
	o.SetMaxDistanceKM(maxDistanceKM)
	return o
}

// SetMaxDistanceKM adds the maxDistanceKM to the nearest using g e t 1 params
func (o *NearestUsingGET1Params) SetMaxDistanceKM(maxDistanceKM *float64) {
	o.MaxDistanceKM = maxDistanceKM
}

// WriteToRequest writes these params to a swagger request
func (o *NearestUsingGET1Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.IndexType != nil {

		// query param indexType
		var qrIndexType string
		if o.IndexType != nil {
			qrIndexType = *o.IndexType
		}
		qIndexType := qrIndexType
		if qIndexType != "" {
			if err := r.SetQueryParam("indexType", qIndexType); err != nil {
				return err
			}
		}

	}

	// query param lat
	qrLat := o.Lat
	qLat := swag.FormatFloat64(qrLat)
	if qLat != "" {
		if err := r.SetQueryParam("lat", qLat); err != nil {
			return err
		}
	}

	// query param lng
	qrLng := o.Lng
	qLng := swag.FormatFloat64(qrLng)
	if qLng != "" {
		if err := r.SetQueryParam("lng", qLng); err != nil {
			return err
		}
	}

	if o.MaxDistanceKM != nil {

		// query param maxDistanceKM
		var qrMaxDistanceKM float64
		if o.MaxDistanceKM != nil {
			qrMaxDistanceKM = *o.MaxDistanceKM
		}
		qMaxDistanceKM := swag.FormatFloat64(qrMaxDistanceKM)
		if qMaxDistanceKM != "" {
			if err := r.SetQueryParam("maxDistanceKM", qMaxDistanceKM); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
