// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// Address Address
// swagger:model Address
type Address struct {

	// city
	City *string `json:"city,omitempty"`

	// country
	Country *string `json:"country,omitempty"`

	// display address1
	DisplayAddress1 *string `json:"displayAddress1,omitempty"`

	// display address2
	DisplayAddress2 *string `json:"displayAddress2,omitempty"`

	// number
	Number *string `json:"number,omitempty"`

	// street
	Street *string `json:"street,omitempty"`
}

// Validate validates this address
func (m *Address) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Address) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Address) UnmarshalBinary(b []byte) error {
	var res Address
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
