// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Coordinates Coordinates
// swagger:model Coordinates
type Coordinates struct {

	// latitude
	// Required: true
	Latitude float64 `json:"latitude"`

	// longitude
	// Required: true
	Longitude float64 `json:"longitude"`
}

// Validate validates this coordinates
func (m *Coordinates) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLatitude(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLongitude(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Coordinates) validateLatitude(formats strfmt.Registry) error {

	if err := validate.Required("latitude", "body", float64(m.Latitude)); err != nil {
		return err
	}

	return nil
}

func (m *Coordinates) validateLongitude(formats strfmt.Registry) error {

	if err := validate.Required("longitude", "body", float64(m.Longitude)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Coordinates) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Coordinates) UnmarshalBinary(b []byte) error {
	var res Coordinates
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
