// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// IndexLevel IndexLevel
// swagger:model IndexLevel
type IndexLevel struct {

	// Color representing this index level, given by hexadecimal css-style triplet
	Color *string `json:"color,omitempty"`

	// Text describing this index level
	Description *string `json:"description,omitempty"`

	// Name of this index level
	Level *string `json:"level,omitempty"`

	// Maximum index value for this level
	MaxValue *float64 `json:"maxValue,omitempty"`

	// Minimum index value for this level
	MinValue *float64 `json:"minValue,omitempty"`

	// Values range for this index level
	Values *string `json:"values,omitempty"`
}

// Validate validates this index level
func (m *IndexLevel) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IndexLevel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IndexLevel) UnmarshalBinary(b []byte) error {
	var res IndexLevel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
