// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// Index Index
// swagger:model Index
type Index struct {

	// Piece of advice from Airly regarding air quality. Text translation is returned according to language specified in the request (English being default)
	Advice *string `json:"advice,omitempty"`

	// Color representing this index level, given by hexadecimal css-style triplet
	Color *string `json:"color,omitempty"`

	// Text describing this air quality level. Text translation is returned according to language specified in the request (English being default)
	Description *string `json:"description,omitempty"`

	// Index level name
	Level *string `json:"level,omitempty"`

	// Name of this index
	Name *string `json:"name,omitempty"`

	// Index numerical value
	Value *float64 `json:"value,omitempty"`
}

// Validate validates this index
func (m *Index) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Index) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Index) UnmarshalBinary(b []byte) error {
	var res Index
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
