// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Measurements Measurements
//
// Current, historical and future measurements.
//
// The 'current' field contains average measurements calculated over a period of last 1 hour.
//
// The 'history' field contains 24 average measurements calculated over periods of last 24 hours.
//
// The 'forecast' field contains 24 future average measurements that we anticipate.
// swagger:model Measurements
type Measurements struct {

	// current
	Current *AveragedValues `json:"current,omitempty"`

	// forecast
	Forecast []*AveragedValues `json:"forecast"`

	// history
	History []*AveragedValues `json:"history"`
}

// Validate validates this measurements
func (m *Measurements) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCurrent(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateForecast(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateHistory(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Measurements) validateCurrent(formats strfmt.Registry) error {

	if swag.IsZero(m.Current) { // not required
		return nil
	}

	if m.Current != nil {
		if err := m.Current.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("current")
			}
			return err
		}
	}

	return nil
}

func (m *Measurements) validateForecast(formats strfmt.Registry) error {

	if swag.IsZero(m.Forecast) { // not required
		return nil
	}

	for i := 0; i < len(m.Forecast); i++ {
		if swag.IsZero(m.Forecast[i]) { // not required
			continue
		}

		if m.Forecast[i] != nil {
			if err := m.Forecast[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("forecast" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *Measurements) validateHistory(formats strfmt.Registry) error {

	if swag.IsZero(m.History) { // not required
		return nil
	}

	for i := 0; i < len(m.History); i++ {
		if swag.IsZero(m.History[i]) { // not required
			continue
		}

		if m.History[i] != nil {
			if err := m.History[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("history" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Measurements) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Measurements) UnmarshalBinary(b []byte) error {
	var res Measurements
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
