// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// MeasurementType MeasurementType
// swagger:model MeasurementType
type MeasurementType struct {

	// Short name of this measurement type. This is a translated field and will contain value according to Access-Language header
	Label *string `json:"label,omitempty"`

	// Identifier of this measurement type. Also used as 'name' identifier in 'measurements' API
	Name *string `json:"name,omitempty"`

	// Unit of this measurement type
	Unit *string `json:"unit,omitempty"`
}

// Validate validates this measurement type
func (m *MeasurementType) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MeasurementType) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MeasurementType) UnmarshalBinary(b []byte) error {
	var res MeasurementType
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
