// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Sponsor Sponsor
// swagger:model Sponsor
type Sponsor struct {

	// description
	Description *string `json:"description,omitempty"`

	// id
	// Required: true
	ID int32 `json:"id"`

	// link
	Link *string `json:"link,omitempty"`

	// logo
	// Required: true
	Logo string `json:"logo"`

	// name
	// Required: true
	Name string `json:"name"`
}

// Validate validates this sponsor
func (m *Sponsor) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLogo(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Sponsor) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", int32(m.ID)); err != nil {
		return err
	}

	return nil
}

func (m *Sponsor) validateLogo(formats strfmt.Registry) error {

	if err := validate.RequiredString("logo", "body", string(m.Logo)); err != nil {
		return err
	}

	return nil
}

func (m *Sponsor) validateName(formats strfmt.Registry) error {

	if err := validate.RequiredString("name", "body", string(m.Name)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Sponsor) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Sponsor) UnmarshalBinary(b []byte) error {
	var res Sponsor
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
